[build]
publish = "www"
command = "npm run build"

[[edge_functions]]
path = "/*"
function = "auth"
excludedPath = [
  "/api/auth/*",
  "/uploads/avatar/*",
  "/api/admin/*",
  "/images/*",
  "/uploads/*",
  "/css/*",
]

[[edge_functions]]
path = "/*"
function = "partial"
excludedPath = ["/api/*", "/images/*", "/uploads/*", "/css/*"]

[[edge_functions]]
path = "/*"
function = "feedback"
excludedPath = ["/api/*", "/images/*", "/uploads/*", "/css/*"]

[[edge_functions]]
path = "/"
function = "latest-posts"

[[redirects]]
from = "/api/:type/*"
to = "/.netlify/functions/:type-:splat"
status = 200

[[redirects]]
from = "/uploads/avatar/:username"
to = "/.netlify/functions/user-avatar?username=:username"
status = 200

[[redirects]]
from = "/images/avatar/small/:username"
to = "/.netlify/images?url=/uploads/avatar/:username&width=256&height=256&fit=cover"
status = 200

[[redirects]]
from = "/images/*"
to = "/.netlify/images?url=/images/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/404.html"
status = 404
